### ISSUE TITLE
Lime error

### ISSUE THREAD

**Issue by felix-tracxpoint** [PrimozGodec/keras-explain#1]
Hi,

I am trying to figure out how to use this toolbox (great project, btw, many thanks for creating it!). I took a model and an image an ran the Lime explainer for them with the correct class prediction - something reasonable came out. Then I randomly changed the target class index to 8 (the model has 89 classes so it's there all right) and got this error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-34-c7232aa8ce1b> in <module>()
      7 print(classIdx, pred[0][classIdx])
      8 
----> 9 pos,neg = explainer.explain(img, 8)

/usr/local/lib/python3.6/site-packages/keras_explain/lime_ribeiro.py in explain(self, image, target_class)
     16             image, self.model.predict, top_labels=5, num_samples=1000)
     17         temp, mask = explanation.get_image_and_mask(
---> 18             target_class, positive_only=False, num_features=10, hide_rest=True)
     19 
     20         return (mask == 2).astype(int), (mask == 1).astype(int)

/usr/local/lib/python3.6/site-packages/lime/lime_image.py in get_image_and_mask(self, label, positive_only, hide_rest, num_features, min_weight)
     49         """
     50         if label not in self.local_exp:
---> 51             raise KeyError('Label not in explanation')
     52         segments = self.segments
     53         image = self.image

KeyError: 'Label not in explanation'
```
Can you help me with this?

Thanks!

**Comment by felix-tracxpoint** [comment]
https://github.com/marcotcr/lime/issues/165

**Comment by PrimozGodec** [comment]
Thank you for using the tool. The issue is that I hardcoded that explanation is made just for the top five labels. I will make a PR with the fix which will allow a user to define a number of top labels.

**Comment by PrimozGodec** [comment]
@felix-tracxpoint I think it is solved by https://github.com/PrimozGodec/keras-explain/pull/2. Please consider reopening the pull request if any issues reappear.
